version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: dcrm
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    restart: always
    environment:
      DB_HOST: db
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/code

volumes:
  db_data:
